### ISSUE TITLE
возникает ошибка UnicodeEncodeError

### ISSUE THREAD

**Issue by prtolem** [WhiteApfel/pyQiwiP2P#32]
когда на дедике запускаю бота то при создании счета возникает ошибка
`UnicodeEncodeError: 'charmap' codec can't encode characters in position 83-90: character maps to <undefined>`

полный трейсбек
```
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-27' coro=<Dispatcher._process_polling_updates() done, defined at C:\Users\admin\AppData\Roaming\Python\Python39\site-packages\aiogram\dispatcher\dispatcher.py:407> exception=UnicodeEncodeError('charmap', '{"serviceName":"payin-invoicing-api","errorCode":"validation.error","description":"Неверные параметры, измените запрос согласно документации API; Cause: unknown","userMessage":"Неверные параметры, измените запрос согласно документации API; Cause: unknown","dateTime":"2022-07-18T23:37:44.061+03:00","traceId":"1ef2ed275a8597e1","cause":{"expirationDateTime":["должно содержать дату, которая еще не наступила"]}}\r\n', 83, 91, 'character maps to <undefined>')>
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Roaming\Python\Python39\site-packages\aiogram\dispatcher\dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "C:\Users\admin\AppData\Roaming\Python\Python39\site-packages\aiogram\dispatcher\dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
  File "C:\Users\admin\AppData\Roaming\Python\Python39\site-packages\aiogram\dispatcher\handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "C:\Users\admin\AppData\Roaming\Python\Python39\site-packages\aiogram\dispatcher\dispatcher.py", line 283, in process_update
    return await self.callback_query_handlers.notify(update.callback_query)
  File "C:\Users\admin\AppData\Roaming\Python\Python39\site-packages\aiogram\dispatcher\handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "C:\Users\admin\Desktop\bot\main.py", line 252, in gen_payment
    bill = p2p.bill(amount=amount, comment='Пополнение баланса')
  File "C:\Users\admin\AppData\Roaming\Python\Python39\site-packages\pyqiwip2p\Qiwip2p.py", line 225, in bill
    qiwi_response = Bill(qiwi_raw_response, self.alt)
  File "C:\Users\admin\AppData\Roaming\Python\Python39\site-packages\pyqiwip2p\p2p_types\responses.py", line 73, in __init__
    Reporter(response).save(fn)
  File "C:\Users\admin\AppData\Roaming\Python\Python39\site-packages\response_report\reporter.py", line 79, in save
    rf.writelines(self.lines)
  File "C:\Program Files\Python39\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 83-90: character maps to <undefined>
```
сделал все согласно документации, ничего не менял кроме комментария

**Comment by ring0jke** [comment]
Столкнулся с той же проблемой, думал я где накосячил, а оказалось нет. Помогиииииитееееее ;(

**Comment by WhiteApfel** [comment]
Юзайте utf-8 для .py файлов

**Comment by WhiteApfel** [comment]
пишут на винде, а потом удивляются, что что-то не работает

**Comment by ring0jke** [comment]
Эт да. 
А вообще @prtolem в моем случае проблема была в другом, я использовал не тот ключ API. Нужен именно приватный ключ полученный на: p2p.qiwi.com
Я же использовал ключ который выдается на главном сайте киви. (qiwi.com)
Сразу все заработало.

**Comment by WhiteApfel** [comment]
@ring0jke, а разве валидатор не поругался на неправильный ключ?

**Comment by ring0jke** [comment]
@WhiteApfel он поругался именно на кодировку,что не смог декодировать ключ.
Ключ был такой примерно : 6fcsda112c499fyt231a8653ddbf15z

**Comment by prtolem** [comment]
> Эт да. 
> А вообще @prtolem в моем случае проблема была в другом, я использовал не тот ключ API. Нужен именно приватный ключ полученный на: p2p.qiwi.com
> Я же использовал ключ который выдается на главном сайте киви. (qiwi.com)
> Сразу все заработало.

нет, токен взял с сайта p2p.qiwi.com
проблему с данной библиотекой вроде не решил, но библиотека glQiwiApi не выдавала такую ошибку так что использовал ее

**Comment by Artem468** [comment]
Столкнулся с такой же проблемой, в чем все таки может быть причина?

**Comment by WhiteApfel** [comment]
@Artem468 , предполагаю, что причина в windows, ибо я не могу воспроизвести в линуксе. Файл с кивикрашем что содержит?

**Comment by Artem468** [comment]
@WhiteApfel  Я тоже решил что причина в винде ведь на основном пк все работает, а на дедике нет, в кивикраш содержится хедерсы и параметры запроса и хедерсы ответа самого ответа нет

**Comment by WhiteApfel** [comment]
Кажется, что приходит одна кодировка, а он пытается записать в другую. Ничего не понятно и не особо интересно\

**Comment by Artem468** [comment]
@WhiteApfel а как это можно исправить?

**Comment by prtolem** [comment]
думаю это может быть связано с тем то что время на пк или дедике не верно указано. У кого возникает данная проблема, попробуйте изменить время на московское, должно помочь
